export default [
  {
  id:1,
    verticalCode: "BUF34000",
    title: "First year applied mathematics / Norman Cannell.",
    author: "Cannell, Norman.",
    callingCode: "510 CAN",
    publishDate: "1956",
  },
  {
  id:2,
    verticalCode: "BUF34001",
    title:
      "A course of mathematics for engineers and scientists/ Brian H. Chirgwin ; Plumpton, Charles.",
    author: "Chirgwin, Brian H.",
    callingCode: "510 CHI",
    publishDate: "1964",
  },
  {
  id:3,
    verticalCode: "BUF34002",
    title:
      "A course of mathematics for engineers and scientists/ Brian H. Chirgwin and Charles Plumpton.",
    author: "Chirgwin, Brian H.",
    callingCode: "510 CHI",
    publishDate: "1972",
  },
  {
  id:3,
    verticalCode: "BUF34003",
    title:
      "An elementary treatise on the dynamics of a particle and of rigid bodies. / S.L. Loney.",
    author: "LONEY , S. L.",
    callingCode: "620.104 LON",
    publishDate: "1960",
  },
  {
  id:5,
    verticalCode: "BUF34004",
    title: "Calculus and analytic geometry. / William H. Durfee.",
    author: "Durfee , William H.",
    callingCode: "515.15 DUR",
    publishDate: "1971",
  },
  {
  id:6,
    verticalCode: "BUF34005",
    title:
      "Science insights : exploring earth and space / Michael DiSpezio [and others].",
    author: "DiSpezio, Michael A.",
    callingCode: "551 FOR",
    publishDate: "?1999.",
  },
  {
    verticalCode: "BUF34006",
    title: "Calculus with analytic geometry / Earl W. Swokowski.",
    author: "Swokowski, Earl William, 1926-",
    callingCode: "515.15 SWO",
    publishDate: "c1988.",
  },
  {
    verticalCode: "BUF34007",
    title: "Calculus and analytic geometry.",
    author: "Stein, Sherman K.",
    callingCode: "515.15 BAR",
    publishDate: "c1992.",
  },
  {
    verticalCode: "BUF34008",
    title: "Calculus with analytic geometry / Earl W. Swokowski.",
    author: "Swokowski, Earl William, 1926-",
    callingCode: "515.15 SWO",
    publishDate: "c1984.",
  },
  {
    verticalCode: "BUF34009",
    title:
      "Calculus with analytic geometry / Howard Anton ; in collaboration with Albert Herr.",
    author: "Anton, Howard.",
    callingCode: "515.15 ANT",
    publishDate: "c1995.",
  },
  {
    verticalCode: "BUF34010",
    title: "Certificate mathematics. Book 3.",
    author: "Fox, R. W. (Ronald William), 1921-",
    callingCode: "510 FOX",
    publishDate: "1963",
  },
  {
    verticalCode: "BUF34011",
    title:
      "A course of mathematics for engineers and scientists / by Brian H. Chirgwin and Charles Plumpton.",
    author: "Chirgwin, Brian H.",
    callingCode: "510 CHI",
    publishDate: "1961",
  },
  {
    verticalCode: "BUF34012",
    title: "Introduction to the Theory of Statistics / Alexander M. Mood",
    author: "Mood, Alexander M.",
    callingCode: "531.12 MOO",
    publishDate: "1963",
  },
  {
    verticalCode: "BUF34013",
    title: "Sixth form pure mathematics. Vol. 2 / C. Plumpton and W.A. Tomkys.",
    author: "Plumpton, C. (Charles), author.",
    callingCode: "510 PLU",
    publishDate: "",
  },
  {
    verticalCode: "BUF34014",
    title: "Calculus and analytica geometry / George B Thomas.",
    author: "Thomas, George B.",
    callingCode: "515.15 THO",
    publishDate: "1960",
  },
  {
    verticalCode: "BUF34015",
    title:
      "A shorter intermediate mechanics / by D. Humphrey and J. Topping ; with diagrams.",
    author: "Humphrey, Douglas, 1880-1945.",
    callingCode: "531 HUM",
    publishDate: "1961",
  },
  {
    verticalCode: "BUF34016",
    title:
      "Higher mathematics: textbook for technical schools/ I. Suvorov ; translated by M. V. Oak ; translation editor: George Yankovsky.",
    author: "Suvorov, I.",
    callingCode: "510 SUV",
    publishDate: "1963",
  },
  {
    verticalCode: "BUF34017",
    title:
      "منبر المسجد الاقصى المبارك : منبر صلاح الدين الأيوبي ( عقد من الإعمار ) جهود الهاشميين في إعادة إعماره / الدكتور غالب عبد أحمد العربيات.",
    author: "عربيات، غالب عبد أحمد مؤلف.",
    callingCode: "956.4 عرب",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34018",
    title:
      "منبر المسجد الاقصى المبارك : منبر صلاح الدين الأيوبي ( عقد من الإعمار ) جهود الهاشميين في إعادة إعماره / الدكتور غالب عبد أحمد العربيات.",
    author: "عربيات، غالب عبد أحمد مؤلف.",
    callingCode: "956.4 عرب",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34019",
    title:
      "منبر المسجد الاقصى المبارك : منبر صلاح الدين الأيوبي ( عقد من الإعمار ) جهود الهاشميين في إعادة إعماره / الدكتور غالب عبد أحمد العربيات.",
    author: "عربيات، غالب عبد أحمد مؤلف.",
    callingCode: "956.4 عرب",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34020",
    title: "المسيحية / تأليف أحمد شلبي.",
    author: "شلبي، أحمد",
    callingCode: "298 شلب",
    publishDate: "2019",
  },
  {
    verticalCode: "BUF34021",
    title: "أديان الهند الكبرى : الهندوسية-الجينية-البوذية / تأليف أحمد شلبي.",
    author: "شلبي، أحمد",
    callingCode: "294 شلب",
    publishDate: "2019",
  },
  {
    verticalCode: "BUF34022",
    title: "الإسلام : مقارنة الأديان / أحمد شلبي.",
    author: "شلبي، أحمد",
    callingCode: "210 شلب",
    publishDate: "2019",
  },
  {
    verticalCode: "BUF34023",
    title:
      "تصنيف ديوي العشري و الكشاف النسبي : ترجمة عربية معدلة ومتوسطة للجداول الرئيسية و المساعدة والكشاف النسبي متوافقة مع الطبعة 23 / ملفل ديوي ؛ تعريب وتعديل الدكتور يونس احمد اسماعيل الشوابكة.",
    author:
      "ديوي، ملفل، 1851-1931 Dewey decimal classification & relative index. Arabic",
    callingCode: "025.431 ديو",
    publishDate: "2018",
  },
  {
    verticalCode: "BUF34024",
    title:
      "تصنيف ديوي العشري و الكشاف النسبي : ترجمة عربية معدلة ومتوسطة للجداول الرئيسية و المساعدة والكشاف النسبي متوافقة مع الطبعة 23 / ملفل ديوي ؛ تعريب وتعديل الدكتور يونس احمد اسماعيل الشوابكة.",
    author:
      "ديوي، ملفل، 1851-1931 Dewey decimal classification & relative index. Arabic",
    callingCode: "025.431 ديو",
    publishDate: "2018",
  },
  {
    verticalCode: "BUF34025",
    title:
      "تصنيف ديوي العشري و الكشاف النسبي : ترجمة عربية معدلة ومتوسطة للجداول الرئيسية و المساعدة والكشاف النسبي متوافقة مع الطبعة 23 / ملفل ديوي ؛ تعريب وتعديل الدكتور يونس احمد اسماعيل الشوابكة.",
    author:
      "ديوي، ملفل، 1851-1931 Dewey decimal classification & relative index. Arabic",
    callingCode: "025.431 ديو",
    publishDate: "2018",
  },
  {
    verticalCode: "BUF34026",
    title:
      "تصنيف ديوي العشري و الكشاف النسبي : ترجمة عربية معدلة ومتوسطة للجداول الرئيسية و المساعدة والكشاف النسبي متوافقة مع الطبعة 23 / ملفل ديوي ؛ تعريب وتعديل الدكتور يونس احمد اسماعيل الشوابكة.",
    author:
      "ديوي، ملفل، 1851-1931 Dewey decimal classification & relative index. Arabic",
    callingCode: "025.431 ديو",
    publishDate: "2018",
  },
  {
    verticalCode: "BUF34027",
    title: "النشمي / شركة البعد الخامس للاعلام.",
    author: "شركة البعد الخامس للإعلام (الأردن).",
    callingCode: "956.505 شرك",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34028",
    title: "النشمي / شركة البعد الخامس للاعلام.",
    author: "شركة البعد الخامس للإعلام (الأردن).",
    callingCode: "956.505 شرك",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34029",
    title: "هندسة السيارات / المهندس هشام محمد المجفت، المهندس محمد نور الصبح.",
    author: "المجفت، هشام محمد،",
    callingCode: "629.2 مجف",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34030",
    title: "علم المواد الهندسية / محمود أحمد عمري.",
    author: "عمري، محمود أحمد",
    callingCode: "620.11 عمر",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34031",
    title:
      "الصحة والسلامة والبيئة المهنية / تأليف المهندس ناصر منصور الروسان، المهندس محمد نور الصبح، المهندسة منار موسى العجلوني، الدكتورة إيمان يونس العبادي.",
    author: "الصبح، محمد نور، مؤلف.",
    callingCode: "613.62 صحة",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34032",
    title:
      "Engineering mechanics Dynamics / R.C. Hibbeler ; SI conversion by Kai Beng Yap.",
    author: "Hibbeler, R. C., author.",
    callingCode: "620.105 HIB",
    publishDate: "",
  },
  {
    verticalCode: "BUF34033",
    title:
      "Dynamics study pack, chapter reviews and free-body diagram workbook : [to accompany] Engineering mechanics. Dynamics, fourteenth edition in SI units [by] R.C. Hibbeler / Peter Schiavone.",
    author: "Schiavone, Peter 1961- author.",
    callingCode: "620.105 HIB",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34034",
    title:
      "Engineering mechanics. Statics / R. C. Hibbeler ; SI conversion by Kai Beng Yap.",
    author: "Hibbeler, R. C., author.",
    callingCode: "620.103 HIB",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34035",
    title: "Structural steel design / Jack C. McCormac, Stephen F. Csernak.",
    author: "McCormac, Jack C., author.",
    callingCode: "624.1821 MCC",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34036",
    title:
      "Electronic devices : conventional current version / Thomas L. Floyd.",
    author: "Floyd, Thomas L., author.",
    callingCode: "621.381 FLO",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34037",
    title:
      "Fundamentals of database systems / Ramez Elmasri, Shamkant B. Navathe.",
    author: "Elmasri, Ramez, author.",
    callingCode: "005.74 MAS",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34038",
    title:
      "Principles of geotechnical engineering / Braja M. Das, Dean Emeritus, California State University, Sacramento, Khaled Sobhan, Florida Atlantic University.",
    author: "Das, Braja M., 1941- author.",
    callingCode: "624.15136 DAS",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34039",
    title:
      "Design of concrete structures / David Darwin, Charles W. Dolan, Arthur H. Nilson.",
    author: "Darwin, David.",
    callingCode: "624.1834 DAR",
    publishDate: "[2016]",
  },
  {
    verticalCode: "BUF34040",
    title:
      "Bioprocess engineering : basic concepts / Michael L. Shuler, Fikret Kargi, Matthew DeLisa.",
    author: "Shuler, Michael L., 1947-",
    callingCode: "660.63 SHU",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34041",
    title:
      "Fundamentals of thermodynamics / Claus Borgnakke, Richard E. Sonntag.",
    author: "Borgnakke, C. (Claus), author.",
    callingCode: "621.4021 BOR",
    publishDate: "[2019]",
  },
  {
    verticalCode: "BUF34042",
    title:
      "Principles of engineering economy / Eugene L. Grant, W. Grant Ireson, Richard S. Leavenworth.",
    author: "Grant, Eugene Lodewick, 1897-",
    callingCode: "658.155 GRA",
    publishDate: "c1990.",
  },
  {
    verticalCode: "BUF34043",
    title:
      "Hacking : the underground guide to computer hacking, including wireless networks, basic security, Windows, Kali Linux and penetration testing / Abraham K White.",
    author: "White, Abraham K.",
    callingCode: "005.8 WHI",
    publishDate: "[2017].",
  },
  {
    verticalCode: "BUF34044",
    title:
      "Wireless communication networks and systems / Cory Beard (University of Missouri-Kansas City), William Stallings.",
    author: "Beard, Cory, author.",
    callingCode: "621.382 BEA",
    publishDate: "[2016]",
  },
  {
    verticalCode: "BUF34045",
    title:
      "Structural Analysis / R.C. Hibbeler, SI conversion by Kai Beng Yap ; with additional SI contributions by Farid Abed.",
    author: "Hibbeler, R. C., author.",
    callingCode: "624.171 HIB",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34046",
    title: "Sheve's chemical process industries/ George T. Austin.",
    author: "Shreve,Randolph Norris, 1885-1975",
    callingCode: "660.2 AUS",
    publishDate: "1984",
  },
  {
    verticalCode: "BUF34047",
    title: "Principles of Automotive Vehicles : Technical Manual TM 9-8000.",
    author: "",
    callingCode: "629.2 PRI",
    publishDate: "20uu.",
  },
  {
    verticalCode: "BUF34048",
    title:
      "Engineering economy / Leland Blank, P.E., Texas A & M University, American University of Sharjah, United Arab Emirates, Anthony Tarquin, P.E., University of Texas at El Paso.",
    author: "Blank, Leland T., author.",
    callingCode: "658.15 BLA",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34049",
    title:
      "Elementary differential equations and boundary value problems / William E. Boyce, Richard C. DiPrima, Douglas B. Meade.",
    author: "Boyce, William E., author.",
    callingCode: "515.35 BOY",
    publishDate: "[2022]",
  },
  {
    verticalCode: "BUF34050",
    title:
      "Engineering circuit analysis / William H. Hayt, Jr, Jack E. Kemmerly and Jamie D. Phillips.",
    author: "Hayt, William H. (William Hart), Jr., 1920-1999, author.",
    callingCode: "621.3815 HAY",
    publishDate: "[2019]",
  },
  {
    verticalCode: "BUF34051",
    title:
      "Materials science and engineering : an introduction / William D. Callister, jr., David G. Rethwisch.",
    author: "Callister, William D., Jr., 1940- author.",
    callingCode: "620.11 CAL",
    publishDate: "[2020]",
  },
  {
    verticalCode: "BUF34052",
    title: "Internal combustion engine fundamentals / John B. Heywood.",
    author:
      "Heywood, John B. (Of the Massachusetts Institute of Technology), author.",
    callingCode: "621.43 HEY",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34053",
    title:
      "Computer forensics : investigating network intrusions and cybercrime / EC-Council Press.",
    author: "EC-Council Press.",
    callingCode: "363.25968 COM",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34054",
    title:
      "Engineering economy / William G. Sullivan, Elin M. Wicks, C. Patrick Koelling.",
    author: "Sullivan, William G., 1942 author.",
    callingCode: "658.15 SUL",
    publishDate: "[2020]",
  },
  {
    verticalCode: "BUF34055",
    title:
      "Mechanical vibrations / Singiresu S. Rao ; SI conversion by Philip Griffin.",
    author: "Rao, Singiresu S., 1944- author.",
    callingCode: "620.3 RAO",
    publishDate: "[2018]",
  },
  {
    verticalCode: "BUF34056",
    title: "Composite materials : design and applications / Daniel Gay.",
    author: "Gay, Daniel, 1942- author.",
    callingCode: "620.118 GAY",
    publishDate: "2023",
  },
  {
    verticalCode: "BUF34057",
    title:
      "Machine Learning : A Comprehensive Step-By-Step Guide to Learning and Understanding Machine Learning Concepts, Technology and Principles for Beginners / Peter Bradley.",
    author: "Bradley, Peter,",
    callingCode: "006.31 BRA",
    publishDate: "2018",
  },
  {
    verticalCode: "BUF34058",
    title:
      "Fundamentals of modern manufacturing : materials, processes, and systems / Mikell P. Groover,",
    author: "Groover, Mikell P., author..",
    callingCode: "670 GRO",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34059",
    title:
      "Water and wastewater engineering : design principles and practice / Mackenzie L. Davis.",
    author: "Davis, Mackenzie Leo, 1941-",
    callingCode: "628.1 DAV",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34060",
    title: "Power plant engineering G. R. Nagpal.",
    author: "",
    callingCode: "621.4 NAG",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34061",
    title:
      "Tech manual to accompany automotive technology : a systems approach / Rob Thompson, Jack Erjavec.",
    author: "Thompson, Rob, author.",
    callingCode: "629.287 THO",
    publishDate: "2020",
  },
  {
    verticalCode: "BUF34062",
    title:
      "Engineering circuit analysis / William H. Hayt, Jr, Jack E. Kemmerly and Jamie D. Phillips.",
    author: "Hayt, William H. (William Hart), Jr., 1920-1999, author.",
    callingCode: "621.3815 HAY",
    publishDate: "[2019]",
  },
  {
    verticalCode: "BUF34063",
    title: "Principles of construction management / Roy Pilcher.",
    author: "Pilcher, Roy.",
    callingCode: "624.068 PIL",
    publishDate: "?1992.",
  },
  {
    verticalCode: "BUF34064",
    title:
      "2000 Errors and English grammar : a reference book for university students, other learners, and teachers of English as a Foreign Language (EFL) / D.r Azmi Adel Moh’d.",
    author: "Mohammad, Azmi Adel Yousef. author.",
    callingCode: "425 MOH",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34065",
    title:
      "2000 Errors and English grammar : a reference book for university students, other learners, and teachers of English as a Foreign Language (EFL) / D.r Azmi Adel Moh’d.",
    author: "Mohammad, Azmi Adel Yousef. author.",
    callingCode: "425 MOH",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34066",
    title:
      "Renewable energy integration : practical management of variability, uncertainty and flexibility in power grids / Lawrence E. Jones.",
    author: "Jones, Lawrence E., author.",
    callingCode: "621.042 JON",
    publishDate: "[2017]",
  },
  {
    verticalCode: "BUF34067",
    title:
      "الرقم (2) والرقم (8) ومعادلة معجزة العلم والعقل / مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف.",
    callingCode: "227.51 ابو",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34068",
    title:
      "الرقم (2) والرقم (8) ومعادلة معجزة العلم والعقل / مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف.",
    callingCode: "227.51 ابو",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34069",
    title: "الرقم(2) والرقم(4) ومعادلة خلق الكون/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34070",
    title: "الرقم(2) والرقم(4) ومعادلة خلق الكون/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34071",
    title:
      "الرقم (1) والرقم (2) والرقم (3) ومعادلة آيات الله في الكون/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34072",
    title:
      "الرقم (1) والرقم (2) والرقم (3) ومعادلة آيات الله في الكون/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34073",
    title:
      "الرقم ثلاثة(3) والرقم سبعة(7) ومعادلة الحياة/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34074",
    title:
      "الرقم ثلاثة(3) والرقم سبعة(7) ومعادلة الحياة/ تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34075",
    title: "الرقم 5 ومعادلة الرحمة والعلم / مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف.",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34076",
    title: "الرقم 5 ومعادلة الرحمة والعلم / مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف.",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34077",
    title: "الرقم (3) الحساب و أرقام الأساس الثلاثة / تأليف مأمون يوسف ابو خضر",
    author: "مأمون يوسف أبو خضر.",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34078",
    title: "الرقم (3) الحساب و أرقام الأساس الثلاثة / تأليف مأمون يوسف ابو خضر",
    author: "مأمون يوسف أبو خضر.",
    callingCode: "227.51 ابو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34079",
    title: "الرقم 7 تمام العد والمالانهايه / تأليف مأمون يوسف ابو خضر",
    author: "مأمون يوسف أبو خضر.",
    callingCode: "227.51 ابو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34080",
    title: "الرقم 7 تمام العد والمالانهايه / تأليف مأمون يوسف ابو خضر",
    author: "مأمون يوسف أبو خضر.",
    callingCode: "227.51 ابو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34081",
    title: "الرقم (8) القوة والعزة / تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34082",
    title: "الرقم (8) القوة والعزة / تأليف مامون يوسف ابو خضر",
    author: "مامون يوسف ابو خضر",
    callingCode: "227.51 ابو",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34083",
    title: "الفوز العظيم / الجزء الأول بقلم الدكتور مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف، مؤلف.",
    callingCode: "225.3 ابو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34084",
    title: "ذكر الله / بقلم الدكتور مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف",
    callingCode: "227.51 أبو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34085",
    title: "خمسة الخير / تأليف مأمون يوسف ابو خضر",
    author: "مأمون يوسف أبو خضر.",
    callingCode: "227.51 ابو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34086",
    title: "جنة القرآن / بقلم مأمون يوسف ابو خضر.",
    author: "مأمون يوسف ابو خضر",
    callingCode: "225.3 ابو",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34087",
    title: "العدد (13) : ميزان خلق الكون / مأمون يوسف أبو خضر.",
    author: "أبو خضر، مأمون يوسف.",
    callingCode: "225.3 أبو",
    publishDate: "2009",
  },
  {
    verticalCode: "BUF34088",
    title: "صيد الخاطر / للإمام أبي الفرج عبدالرحمن بن الجوزي.",
    author: "ابن الجوزي، عبد الرحمن بن علي بن محمد، 508-597 هـ.",
    callingCode: "215.1 ابن",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34089",
    title: "ملكوت الواقع : ممهدات وحوافز قبل الإنطلاق / أحمد خيري العمري.",
    author: "العمري، أحمد خيري.",
    callingCode: "271.2 عمر",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34090",
    title: "الجرة : قصص قصيرة / محمد حسين السماعنة.",
    author: "السماعنة، محمد حسين عبد الرحيم",
    callingCode: "813.01 سما",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34091",
    title:
      "Fundamentals of analytical chemistry / Douglas A. Skoog, Donald M. West.",
    author: "Skoog, Douglas A.",
    callingCode: "543 SKO",
    publishDate: "c1976.",
  },
  {
    verticalCode: "BUF34092",
    title:
      "Organic chemistry / James B. Hendrickson. Donald J. Cram. George S. Hammond.",
    author: "Hendrickson , James Briggs , 1928-.",
    callingCode: "547 HEN",
    publishDate: "1970",
  },
  {
    verticalCode: "BUF34093",
    title:
      "Best & Taylor's physiological basis of medical practice/ edited by John R. Brobeck.",
    author: "Best, Charles Herbert, 1899.",
    callingCode: "612 BES",
    publishDate: "1979",
  },
  {
    verticalCode: "BUF34094",
    title: "Basic biology / Richard A. Goldsby.",
    author: "Goldsby, Richard A.",
    callingCode: "574 GOL",
    publishDate: "?1976.",
  },
  {
    verticalCode: "BUF34095",
    title: "Chemical Principles / William L. Masterton , Emil J. Slowinski.",
    author: "Masterton, William L.",
    callingCode: "540 MAS",
    publishDate: "1977",
  },
  {
    verticalCode: "BUF34096",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34097",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34098",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34099",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34100",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34101",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34102",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34103",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34104",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34105",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34106",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34107",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34108",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34109",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34110",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34111",
    title: "دعيني أحبك / شعر ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد،",
    callingCode: "811.9 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34112",
    title:
      "زيد الحرب والعزف على أوتار الأمة : ندوة 27 ديسمبر 2004 / محاضرة د. حصة سيد زيد الرفاعي ؛ تعقيب د. صباح السويفان ؛ تحرير غنيمة زيد الحرب.",
    author: "الرفاعي، حصة السيد زيد، محاضر.",
    callingCode: "811.9566809 رفا",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34113",
    title: "ترجمان السنة/ عائض بن عبد الله القرني.",
    author: "عائض بن عبد الله القرني، 1959.",
    callingCode: "213.1 قرن",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34114",
    title: "تاريخ التشريع الإسلامي : (التشريع والفقة) / مناع القطان.",
    author: "القطان، مناع",
    callingCode: "260.9 قطا",
    publishDate: "1997",
  },
  {
    verticalCode: "BUF34115",
    title:
      "عمان في مطلع القرن العشرين : السجل الشرعي الأول لناحية عمان 1319-1326 هـ. / 1902-1908 م : دراسة وتحقيق / تأليف صلاح يوسف قازان.",
    author: "قازان، صلاح يوسف",
    callingCode: "956.511 قاز",
    publishDate: "]2010]",
  },
  {
    verticalCode: "BUF34116",
    title:
      "رسائل ابن عربي : كشف الستر / تأليف محي الدين ابو بكر محمد بن علي الطائي ابن عربي ؛ تحقيق قاسم محمد عباس.",
    author: "ابن عربي، محي الدين أبو بكر محمد بن علي بن محمد، 560-638 هـ.",
    callingCode: "219.1 عرب",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34117",
    title: "هي لعبة...ولكن / عمر الخواجا.",
    author: "الخواجا، عمر، مؤلف.",
    callingCode: "ق عمر",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34118",
    title:
      "الحماية القانونية لبرامج الحاسب الآلي : حماية البرامج بأحكام حق author / عزة علي محمد الحسن.",
    author: "الحسن، عزة علي محمد.",
    callingCode: "346.0482 حسن",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34119",
    title: "الأردن سنوان القلق والدم والتطرف/ سميح المعايطة.",
    author: "المعايطة، سميح.",
    callingCode: "320.9565 معا",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34120",
    title: "جدار الانتظار : شعر / محمود فضيل التل.",
    author: "التل، محمود فضيل، 1940-, مؤلف.",
    callingCode: "811.9565 محم",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34121",
    title:
      "أطفالنا ومشكلاتهم التربوية والنفسية : أسبابها والوقاية منها / مصطفى رجب.",
    author: "رجب، مصطفى",
    callingCode: "155.4 رجب",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34122",
    title: "دراكولا/ ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد، مؤلف",
    callingCode: "813.03 عسق",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34123",
    title:
      "خبز وخوف : رواية / فيصل يوسف عوض الشبول ؛ لوحة الغلاف بريشة الفنان عماد حجاج ؛ الصف الضوئي مركز الطيف الرقمي.",
    author: "الشبول، فيصل يوسف عوض، 1958- مؤلف.",
    callingCode: "ق شبو",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34124",
    title:
      "القيادة والتدريب في الحركة الكشفية / محمود داود الربيعي، أحمد بدري حسين.",
    author: "الربيعي، محمود داود سلمان",
    callingCode: "369.43 ربي",
    publishDate: "2001",
  },
  {
    verticalCode: "BUF34125",
    title: "الهندسة الكهربائية للتبريد وتكيف الهواء/ تأليف صبري بولس",
    author: "صبري بولس",
    callingCode: "697.93 بول",
    publishDate: "-198",
  },
  {
    verticalCode: "BUF34126",
    title: "فنون النجارة الحديثة للهواه و المحترفين / فتحي محمد صالح.",
    author: "صالح، فتحي محمد مؤلف.",
    callingCode: "694 صال",
    publishDate: "1990",
  },
  {
    verticalCode: "BUF34127",
    title: "معالم الثقافة الاسلامية / عبد الكريم عثمان.",
    author: "عثمان، عبد الكريم.",
    callingCode: "211 عثم",
    publishDate: "2001",
  },
  {
    verticalCode: "BUF34128",
    title: "تجليات القدس في الشعر المعاصر / محمد حور.",
    author: "حور, محمد",
    callingCode: "811.9564 حور",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34129",
    title: "تجليات الأدب العربي في عصر الحروب الصليبية / عمر عبدالله العنبر.",
    author: "العنبر، عمر عبد الله",
    callingCode: "811.9074 عنب",
    publishDate: "2021",
  },
  {
    verticalCode: "BUF34130",
    title: ":Sharon and my mother-in-law Ramallah diaries / Suad Amiry.",
    author: "Amiry, Suad.",
    callingCode: "956.9542 AMI",
    publishDate: "c2004.",
  },
  {
    verticalCode: "BUF34131",
    title: "موت الأبيض شبيهي : شعر / عبد الله رضوان.",
    author: "رضوان، عبد الله، 1949-",
    callingCode: "811.9 رضو",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34132",
    title:
      "الفضاءات الداخلية .... للاستكشافات الباراسايكولوجية للعقل / هاوارد ايزنبرغ، ترجمة الحارث عبد الحميد ، أسيل عبد الرازق، مراجعة عبد الامير الأعسم",
    author: "ايزبنرغ، هاوارد.",
    callingCode: "133 ايز",
    publishDate: "2001",
  },
  {
    verticalCode: "BUF34133",
    title: "دليل فودورز السياحي : هونغ كونغ مع رحلات إلى الصين ومكاو.",
    author: "",
    callingCode: "915 دلي",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34134",
    title: "العولمة وتاريخ الصراع مع الغرب / رعد شمس الدين الكيلاني.",
    author: "الكيلاني، رعد شمس الدين.",
    callingCode: "956 كيل",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34135",
    title: "المتفوقون-الموهوبون-المبدعون / عبد المنعم عبد القادر الميلادي.",
    author: "الميلادي، عبد المنعم عبد القادر",
    callingCode: "371.95 ميل",
    publishDate: "2003",
  },
  {
    verticalCode: "BUF34136",
    title:
      "ضمانات المرأة في حقوق الإنسان / لمياء ياسين الركابي، ياسين محمد العيثاوي.",
    author: "الركابي، لمياء ياسين.",
    callingCode: "323.34 ركا",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34137",
    title: "كيف تستخدم Internet / ترجمة وإعداد نبيل كوراني.",
    author: "كوراني، نبيل مترجم.",
    callingCode: "004.678 كيف",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34138",
    title: "في الطريق إلى عمان/ فالح الطويل.",
    author: "الطويل، فالح.",
    callingCode: "818.0309565 فال",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34139",
    title:
      "عبد الله خالد الحاتم : ندوة 15 ديسمبر 2004 : محاضرة خالد سالم محمد، عبد الله خلف.",
    author: "ندوة عبد الله خالد الحاتم (2004 : الكويت)",
    callingCode: "810.9095694 ندو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34140",
    title: "فلسطين : دور العقل والخلق في معركة التحرير / وصفي التل.",
    author: "التل، وصفي مصطفى وهبي، 1919-1971",
    callingCode: "956.403 وصف",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34141",
    title:
      "كل شئ عن المياه في العالم : هل تكفي المياه أحفادنا/ أو . أ .سبنغلر ؛ ترجمة مناع شكري الفريجات.",
    author: "سبنغلر، أو . أ،",
    callingCode: "551.48 سبن",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34142",
    title: "تلك الأيام / تأليف فوز الدين البسومي.",
    author: "البسومي، فوز الدين، 1936-",
    callingCode: "ق بسو",
    publishDate: "1980",
  },
  {
    verticalCode: "BUF34143",
    title:
      "دعوة نبي الله عيسى علية السلام إلى التوحيد وفق التوراة والإنجيل / شاكر توفيق العاروري.",
    author: "العاروري , شاكر توفيق أمين",
    callingCode: "228.228 عار",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34144",
    title: "الوابل الصيب من الكلم الطيب/ ابن قيم الجوزية.",
    author:
      "ابن قيم الجوزية، شمس الدين أبو عبد الله محمد بن أبي بكر، 691-752 هـ.",
    callingCode: "218 ابن",
    publishDate: "1982",
  },
  {
    verticalCode: "BUF34145",
    title: "سبيل أهل القرآن / أحمد محمد مفلح القضاة.",
    author: "القضاة، أحمد محمد مفلح.",
    callingCode: "227.4 قضا",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34146",
    title: "كن مع الله / شيرين منير النجار.",
    author: "النجار، شيرين منير.",
    callingCode: "210.8 نجا",
    publishDate: "2007-2011",
  },
  {
    verticalCode: "BUF34147",
    title: "مع الله في السماء / أحمد زكي.",
    author: "زكي، أحمد، 1894-1975",
    callingCode: "216.5 زكي",
    publishDate: "198u",
  },
  {
    verticalCode: "BUF34148",
    title: "رحلة العشرين عاماً : نصوص / أحمد جابر.",
    author: "جابر، أحمد",
    callingCode: "819.9 جاب",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34149",
    title:
      "حقوق المتهم أثناء التحقيق الابتدائي : دراسة مقارنة بين التشريع الإسلامي والقانون الجنائي الأردني / إعداد محمود هارون النوافلة.",
    author: "النوافلة، محمود هارون.",
    callingCode: "210.4345056 نوا",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34150",
    title: "وداعا للسلاح / أرنست همنغواي ؛ ترجمة كريم نايف.",
    author: "همنجواي، إرنست ميلر، 1899-1961",
    callingCode: "ق همن",
    publishDate: "1975",
  },
  {
    verticalCode: "BUF34151",
    title: "دماء الفجر وحناء الأجنحة / شعر هلال الفارع.",
    author: "الفارع، هلال",
    callingCode: "811.9 فار",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34152",
    title: "قمصدر / ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد، مؤلف",
    callingCode: "811.9 عسق",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34153",
    title: "قمصدر / ظافر خالد عسقلان.",
    author: "عسقلان، ظافر خالد، مؤلف",
    callingCode: "811.9 عسق",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34154",
    title:
      "موسوعة فن عمل الأزهار والرسم على الزجاج والتطريز والخزف والزخرفة / إعداد أميرة الخطيب.",
    author: "الخطيب، أميرة",
    callingCode: "745.5 خطي",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34155",
    title: "رجال في تاريخ الأردن / إعداد أحمد عبد الرحيم حوراني.",
    author: "حوراني، أحمد عبد الرحيم. author.",
    callingCode: "920.0565 حور",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34156",
    title: "المذنب : مجموعة قصصية / أسماء الملاح.",
    author: "الملاح، أسماء",
    callingCode: "ق ملا",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34157",
    title:
      "الإبداع في الإنشاء / زيد موسى أبو زيد، ياسر خالد سلامة ؛ تدقيق لغوي سناء خضير.",
    author: "زيد موسى أبو زيد.",
    callingCode: "418.2 ابو",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34158",
    title: "قدر ..أم حذر؟ وقصص أخرى / تأليف الدكتورة زينب بيرة جكلي.",
    author: "جكلي، زينب محمد صبري بيرة",
    callingCode: "813.01 جكل",
    publishDate: "1997",
  },
  {
    verticalCode: "BUF34159",
    title: "ربيع العمر: كتابات في الصحة والحياة / زهير ابو فارس.",
    author: "أبو فارس، زهير",
    callingCode: "613 ابو",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34160",
    title: "عمان : عاصمة الأردن / سليمان الموسى",
    author: "الموسى، سليمان",
    callingCode: "956.511 موس",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34161",
    title: "في رحاب السنة / محمد مصطفى ابو هاشم.",
    author: "ابو هاشم، محمد مصطفى،",
    callingCode: "230 ابو",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34162",
    title: "عالم البرزخ / رغداء بكور الياقتي.",
    author: "الياقتي، رغداء بكور",
    callingCode: "244.64 ياق",
    publishDate: "2009",
  },
  {
    verticalCode: "BUF34163",
    title: "الإسلام و بناء المجتمع / فرج محمود حسن أبو ليلى.",
    author: "فرج محمود حسن أبو ليلى",
    callingCode: "218 ابو",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34164",
    title:
      "دعوني أتكلم : شهادة امرأة من المناجم البوليفية / دوميتيلا دوشنغارا ؛ ترجمة سمية فلو.",
    author: "دوشنغارا، دوميتيلا باريوس",
    callingCode: "301.4120984 دوش",
    publishDate: "1980",
  },
  {
    verticalCode: "BUF34165",
    title:
      "A dictionary of islamic words and expressions : = Arabic-English, with an Arabic index / معجم الألفاظ والتعابير الإسلامية - عربي-إنجليزي مع مسرد باللغة العربية by Mahmoud Isma'il Saleh ; revised and ecited by Translation Unit of Al-Jumuah Magazine.",
    author: "Saleh, Mahmoud Ismail.",
    callingCode: "210.3 SAL",
    publishDate: "?2001.",
  },
  {
    verticalCode: "BUF34166",
    title:
      "لا تتجاهل / هارون يحيى ؛ ترجمة ميسون نحلاوي ؛ مراجعة أورخان محمد علي.",
    author: "يحيى، هارون",
    callingCode: "218 يحي",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34167",
    title: "دوحة الصالحات / عبد الرحيم مارديني.",
    author: "مارديني، عبد الرحيم .",
    callingCode: "272.27 مار",
    publishDate: "200u.",
  },
  {
    verticalCode: "BUF34168",
    title:
      "Computer Skills- Basics & 2 : مهارات الحاسوب - تقوية 2 / (ect...)Nael Hirzallah",
    author: "Nael Hirzallah",
    callingCode: "004 COM",
    publishDate: "0.2014",
  },
  {
    verticalCode: "BUF34169",
    title: "تعلم خط الرقعة / سعادة عودة أبو عراق، سندس أبو عراق.",
    author: "أبو عراق، سعادة عودة.",
    callingCode: "411.4 ابو",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34170",
    title: "النقد النسقي : تمثيلات النسق في الشعر الجاهلي / يوسف محمود عليمات.",
    author: "عليمات، يوسف محمود، مؤلف.",
    callingCode: "811.109 علي",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34171",
    title: "فن المقالة في الأردن / تحرير شكري الماضي، هند أبو الشعر.",
    author: "ملتقى عمان الثقافي (3 : 1999 : المفرق، الأردن)",
    callingCode: "814.90565 فنا",
    publishDate: "",
  },
  {
    verticalCode: "BUF34172",
    title:
      "إستخدام البريد الإلكتروني للوصول إلى كافة موارد الإنترنت = E-mail/ الايهم صالح.",
    author: "صالح، الايهم.",
    callingCode: "004.692 صال",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34173",
    title: "لغة البرمجة C : مدخل هام إلى ++C/ فادي حجار.",
    author: "فادي حجار",
    callingCode: "005.133 حجا",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34174",
    title: "الطريق إلى إحتراف ++visual c/ عزب محمد عزب.",
    author: "عزب، عزب محمد.",
    callingCode: "005.133 عزب",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34175",
    title:
      "الشباب وعالم جديد / عادل الطويسي ... [وآخ.] ؛ مراجعة وتقديم تيسير أبو عرجة.",
    author: "الطويسي، عادل.",
    callingCode: "305.242 شبا",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34176",
    title: "وفاء بلا ثمن : قصص قصيرة / أميرة السويدي.",
    author: "السويدي، أميرة،",
    callingCode: "813.01 سوي",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34177",
    title: "نبض القصيد : شعر / علي غبن.",
    author: "غبن، علي،",
    callingCode: "811.9 غبن",
    publishDate: "2021",
  },
  {
    verticalCode: "BUF34178",
    title:
      "استلهام التراث، وتوظيفه في شعر محمود درويش( 1982م - 1993م ) / د. سهى حسن مشرقي.",
    author: "مشرقي، سهى حسن عبد الله",
    callingCode: "811.9564 مشر",
    publishDate: "2022",
  },
  {
    verticalCode: "BUF34179",
    title: "المواعظ العريفية / محمد العريفي.",
    author: "العريفي، محمد.",
    callingCode: "218 عري",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34180",
    title:
      "عقيدة المؤمن : كتاب يبحث في العقيدة الإسلامية .../ ابو بكر جابر الجزائري.",
    author: "جزائري , أبو بكر جابر",
    callingCode: "240 جزا",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34181",
    title: "A year down yonder / Richard Peck.",
    author: "Peck, Richard, 1934-2018.",
    callingCode: "823.54 PEC",
    publishDate: "[2000]",
  },
  {
    verticalCode: "BUF34182",
    title:
      "عمان و جوارها خلال الفترة 1281هـ/1864م - 1340هـ/1921م / نوفان رجا الحمود السوارية.",
    author: "نوفان رجا الحمود السوارية.",
    callingCode: "956.511 سوا",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34183",
    title:
      "تاريخ حركة الإستشراق : الدراسات العربية والاسلامية في اوروبا حتى بداية القرن العشرين / يوهان فوك ؛ ترجمة عمر لطفي العالم.",
    author: "فوك، يوهان.",
    callingCode: "956 فوك",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34184",
    title:
      "Eight lives down : the story of a counter-terrorist bomb-disposal operator's tour in Iraq / Chris Hunter.",
    author: "Hunter, Chris.",
    callingCode: "956.7443341092 HUN",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34185",
    title:
      "الشباب وظاهرة العنف : أعد هذا الكتاب استنادا إلى وقائع المؤتمر الشبابي الذي عقده المنتدى في الإسكندرية في الفترة من 13-15/12/2010 / اشراف الدكتور الصادق الفقيه، تحرير محمد سلام جميعان، مراجعة كايد هاشم.",
    author:
      "مؤتمر الشباب وظاهرة العنف (الرابع : 13-15 / 12 / 2010 : عمان، الاردن)",
    callingCode: "362.7 مؤت",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34186",
    title:
      "جرش : تاريخها وحضارتها : تاريخها وحضارتها : دراسة في الموقع والسكان، وصف الآثار، جرش الحديثة / أسامة يوسف شهاب.",
    author: "شهاب، أسامة يوسف، 1957-",
    callingCode: "956.522 شها",
    publishDate: "1989",
  },
  {
    verticalCode: "BUF34187",
    title:
      "ENGLISH idioms and speech forms which cause difficulties to Arab students/ edited by Adnan Yousef Dajani ; ;with a foreword by Kevin Purday.",
    author: "Adnan Yousef Dajani Editor.",
    callingCode: "428.24 ENG",
    publishDate: "2001",
  },
  {
    verticalCode: "BUF34188",
    title: "The world's greatest mistakes / Nigel Blundell.",
    author: "Blundell, Nigel.",
    callingCode: "032.02 BLU",
    publishDate: "1991, ?1980.",
  },
  {
    verticalCode: "BUF34189",
    title: "محمد رسول الله تحاربه قوى الشر والتخريب / أحمد عبد الغفور عطار.",
    author: "عطار، أحمد بن عبد الغفور بن محمد نور، 1337-1411 هجريا.",
    callingCode: "219 عطا",
    publishDate: "1988",
  },
  {
    verticalCode: "BUF34190",
    title:
      "خطب الشيخ محمد الغزالي في شؤون الدين والحياة / إعداد قطب عبد الحميد قطب ؛ مراجعة محمد أحمد عاشور ؛ تصدير بقلم عبد الصبور شاهين.",
    author: "الغزالي، محمد بن محمد بن محمد، 450-505 هـ.",
    callingCode: "218.2 غزا",
    publishDate: "1988",
  },
  {
    verticalCode: "BUF34191",
    title: "عابر سرير : رواية / أحلام مستغانمي.",
    author: "مستغانمي، أحلام، 1953-",
    callingCode: "ق مست",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34192",
    title: "ذاكرة الجسد : رواية / أحلام مستغانمي.",
    author: "مستغانمي، أحلام، 1953-",
    callingCode: "ق مست",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34193",
    title:
      "لعنة الفراعنة : التفسير العلمي لظاهرة لعنة الفراعنة الغامضة / فيليب فاندنبرغ ؛ ترجمة خالد أسعد عيسى، أحمد غسان سبانو.",
    author: "فاندنبرغ، فيليب",
    callingCode: "932.01 فان",
    publishDate: "2004",
  },
  {
    verticalCode: "BUF34194",
    title:
      "الشعر العربي الحديث : أعمال الندوة الرئيسية [لمهرجان القرين الثقافي الثاني عشر، 10-12 ديسمبر 2005] / المجلس الوطني للثقافة والفنون والآداب ؛ [إعداد] بدر سيد عبد الوهاب الرفاعي.",
    author: "ندوة الشعر العربي الحديث (2005 : الكويت)",
    callingCode: "811.9 ندو",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34195",
    title: "الخيال من الكهف إلى الواقع الافتراضي / تأليف د. شاكر عبد الحميد.",
    author: "عبد الحميد، شاكر، 1952- مؤلف.",
    callingCode: "153.3 عبد",
    publishDate: "2009",
  },
  {
    verticalCode: "BUF34196",
    title: "من روائع العريفي / تأليف د. محمد عبد الرحمن العريفي.",
    author: "العريفي، محمد بن عبد الرحمن، 1390 هجريا- ، مؤلف.",
    callingCode: "215.1 عري",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34197",
    title: "العقائد الإسلامية / السيد سابق.",
    author: "سابق، السيد، ت. 1420 هـ.",
    callingCode: "240 ساب",
    publishDate: "199u.",
  },
  {
    verticalCode: "BUF34198",
    title:
      "الداء والدواء، أو، الجواب الكافي لمن سأل عن الدواء الشافي / لابن قيم الجوزية ؛ دراسة وتحقيق محمد عثمان الخشت.",
    author: "ابن قيم الجوزية، محمد بن أبي بكر بن أيوب، 691-751 هـ.",
    callingCode: "218.2 قيم",
    publishDate: "1988",
  },
  {
    verticalCode: "BUF34199",
    title:
      "المرأة المسلمة ومسئولياتها في الواقع المعاصر : دراسة تأصيلية شرعا وواقعا / تأليف فالح محمد الصغير.",
    author: "الصغير، فالح بن محمد بن فالح، 1377 هجريا-.",
    callingCode: "265.4 صغي",
    publishDate: "[2009]",
  },
  {
    verticalCode: "BUF34200",
    title:
      "روضة الأنوار في سيرة النبي المختار صلى الله عليه وسلم / تأليف صفي الرحمن المباركفوري.",
    author: "المباركفوري، صفي الرحمن، 1943-2006",
    callingCode: "239 مبا",
    publishDate: "[2009] 1430.",
  },
  {
    verticalCode: "BUF34201",
    title:
      "روضة الأنوار في سيرة النبي المختار صلى الله عليه وسلم / تأليف صفي الرحمن المباركفوري.",
    author: "المباركفوري، صفي الرحمن، 1943-2006",
    callingCode: "239 مبا",
    publishDate: "[2009] 1430.",
  },
  {
    verticalCode: "BUF34202",
    title:
      "الأخلاق الفاضلة : قواعد ومنطلقات لاكتسابها عصارة أفكار وتجارب من معترك الحياة في ضوء كتاب الله وحديث رسول الله صلى الله عليه وسلم / تأليف عبد الله بن ضيف الله الرحيلي.",
    author: "الرحيلي، عبد الله بن ضيف الله راجح، 1372 هجريا-",
    callingCode: "212 رحي",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34203",
    title:
      "الأخلاق الفاضلة : قواعد ومنطلقات لاكتسابها عصارة أفكار وتجارب من معترك الحياة في ضوء كتاب الله وحديث رسول الله صلى الله عليه وسلم / تأليف عبد الله بن ضيف الله الرحيلي.",
    author: "الرحيلي، عبد الله بن ضيف الله راجح، 1372 هجريا-",
    callingCode: "212 رحي",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34204",
    title: "خلاصة الكلام في أركان الإسلام / عبد الله بن محمد بن أحمد الطيار.",
    author: "الطيار، عبد الله بن محمد بن أحمد، 1373 هـ-",
    callingCode: "216 طيا",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34205",
    title:
      "جوهر الدعاء : ويليه حرص الأنبياء على دعاء إبراهيم الخليل صلى الله علية وسلم ( ربنا و تقبل دعاء ) / جمع وترتيب زياد الرحاحلة.",
    author: "",
    callingCode: "271.612 جوه",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34206",
    title:
      "جوهر الدعاء : ويليه حرص الأنبياء على دعاء إبراهيم الخليل صلى الله علية وسلم ( ربنا و تقبل دعاء ) / جمع وترتيب زياد الرحاحلة.",
    author: "",
    callingCode: "271.612 جوه",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34207",
    title: "شؤون وقضايا مسرحية / فرحان بلبل.",
    author: "بلبل، فرحان.",
    callingCode: "812.9 بلب",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34208",
    title: "قلوبهم معنا وقنابلهم علينا / أحلام مستغانمي.",
    author: "مستغانمي، أحلام، 1953-",
    callingCode: "320.9563 مست",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34209",
    title: "فرج : رواية / رضوى عاشور .",
    author: "رضوى عاشور.",
    callingCode: "813.03 عاش",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34210",
    title:
      "سورة الصلاة : ترتج بها المساجد والمصليات .. ولكن !! / تأليف عبد الحكيم بن عبدالله القاسم.",
    author: "عبد الحكيم بن عبدالله القاسم.",
    callingCode: "221.51 قاس",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34211",
    title: "70 جائزة ربانية / عبد الله حمود البوسعيدي.",
    author: "البوسعيدي، عبد الله بن حمود",
    callingCode: "234.11 بوس",
    publishDate: "2003",
  },
  {
    verticalCode: "BUF34212",
    title:
      "عقوق الوالدين : مظاهره- اسبابه- سبل العلاج/ تأليف محمد بن ابراهيم الحمد.",
    author: "الحمد، محمد بن ابراهيم",
    callingCode: "218.2 حمد",
    publishDate: "[2005]",
  },
  {
    verticalCode: "BUF34213",
    title: "الوعد الحق / طه حسين.",
    author: "طه حسين، 1889-1973.",
    callingCode: "ق حسي",
    publishDate: "1976",
  },
  {
    verticalCode: "BUF34214",
    title:
      "إشراقات تربوية : عرض صور ونماذج لجوانب هامة في التربية / تأليف مريم عبد الله عبد الرحمن النعيمي.",
    author: "النعيمي، مريم عبد الله عبد الرحمن",
    callingCode: "218.3 نعي",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34215",
    title:
      "اقتراحات : أكثر من 100 اقتراح إيماني، اجتماعي، تربوي، أسري، إداري / عبد الله البوسعيدي.",
    author: "البوسعيدي، عبد الله بن حمود",
    callingCode: "218.3 بوس",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34216",
    title: "فرسان من مدرسة النبوة / تأليف عبد الرحمن عميرة.",
    author: "عميرة، عبد الرحمن",
    callingCode: "239.5 عمي",
    publishDate: "[198-",
  },
  {
    verticalCode: "BUF34217",
    title: "الكذابون : مدعو النبوة في التاريخ الإسلامي / طارق سرى.",
    author: "سرى، طارق،",
    callingCode: "956.03 سرى",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34218",
    title: "حبيبتي بكماء : رواية / محمد بدر السالم.",
    author: "السالم، محمد بدر،",
    callingCode: "813.03 سال",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34219",
    title:
      "أنطولوجيا : القصة الإيرانية الحديثة / تأليف مجموعة من الأدباء الإيرانيين.",
    author: "",
    callingCode: "891.55 انط",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34220",
    title:
      "إدارة المخيمات : الأسس الفنية والقانونية لإدارة مخيمات اللاجئين وفقا للقوانين والتشريعات الدولية والوطنية / محمد ابراهيم ابداح.",
    author: "إبداح، محمد إبراهيم",
    callingCode: "341.486 ابد",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34221",
    title: "تحقيقات أدبية / ناصر الدين الأسد.",
    author: "الأسد، ناصر الدين، 1923-",
    callingCode: "810.9 اسد",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34222",
    title: "قصص من السيرة النبوية العطرة / سامي عبدالرحمن قباجة.",
    author: "قباجة، سامي عبدالرحمن،",
    callingCode: "239 قبا",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34223",
    title: "اللغة : نشأتها، وتطورها في الفكر والإستعمال / حسن سعيد الكرمي.",
    author: "الكرمي، حسن سعيد مؤلف.",
    callingCode: "401 كرم",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34224",
    title:
      "جلالة الملك عبد الله الثاني ودوره في محاربة التطرف والإرهاب : دراسة في الأوراق النقاشية ورسالة عمان / محمود علي عواد الحراحشة.",
    author: "الحراحشة، محمود علي عواد،",
    callingCode: "956.505 حرا",
    publishDate: "2021",
  },
  {
    verticalCode: "BUF34225",
    title: "في الطريق إلى عمان/ فالح الطويل.",
    author: "الطويل، فالح.",
    callingCode: "818.0309565 فال",
    publishDate: "2010",
  },
  {
    verticalCode: "BUF34226",
    title: "حجر النرد الأخير : رواية / سارة الزير.",
    author: "الزير، سارة،",
    callingCode: "813.03 زير",
    publishDate: "200u.",
  },
  {
    verticalCode: "BUF34227",
    title: "ربيع آخر : رواية / تاكاشي تسوجي ؛ ترجمة فخري صالح.",
    author: "تسوجي، تاكاشي.",
    callingCode: "813.03 تسو",
    publishDate: "1997",
  },
  {
    verticalCode: "BUF34228",
    title: "دعوة الإسلام / السيد سابق.",
    author: "سابق، السيد، ت. 1420 هـ مؤلف.",
    callingCode: "215.2 ساب",
    publishDate: "1980z",
  },
  {
    verticalCode: "BUF34229",
    title:
      "فقه الزكاة : دراسة مقارنة لأحكامها و فلسفتها في ضوء القرآن و السنة / تأليف يوسف القرضاوي.",
    author: "قرضاوي، يوسف.",
    callingCode: "271.4 قرض",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34230",
    title: "هي القدس : ديوان شعر / نبيلة الخطيب.",
    author: "الخطيب، نبيلة.",
    callingCode: "811.9565 خطي",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34231",
    title: "نساء وراء القضبان : أشهر النساء في عالم الإجرام، أيمن أبو الروس.",
    author: "ابو الروس، ايمن.",
    callingCode: "364.37 ابو",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34232",
    title:
      "أحمد مطر : شاعر المنفى : أحدث وأجمل قصائد الشاعر العربي أحمد مطر / إعداد محمد عصام عايش.",
    author: "عايش، محمد عصام",
    callingCode: "811.9 عاي",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34233",
    title: "الامير السعيد و قصص اخرى / اوسكار وايلد ؛ ترجمة ممدوح حسن لطفي.",
    author: "وايلد، اوسكار مؤلف",
    callingCode: "813.01 واي",
    publishDate: "1900",
  },
  {
    verticalCode: "BUF34234",
    title: "رياح الزمن : شعر / أحمد نصر الله.",
    author: "نصر الله، أحمد",
    callingCode: "811.9565 نصر",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34235",
    title: "أعلام وشخصيات من بلادي / محمد سمحان.",
    author: "سمحان، محمد",
    callingCode: "920.0565 سمح",
    publishDate: "1998",
  },
  {
    verticalCode: "BUF34236",
    title: "السعادة : موجز تاريخي / تأليف نيكولاس وايت ؛ ترجمة سعيد توفيق.",
    author: "وايت، نيكولاس مؤلف.",
    callingCode: "158 واي",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34237",
    title:
      "مبادئ النقد التطبيقي في النظرية والتطبيق : دراسة داخل النص العربي القديم والحديث / عماد الخطيب، كمال جبري.",
    author: "الخطيب، عماد علي سليم أحمد، 1972-",
    callingCode: "810.9 خطي",
    publishDate: "2003",
  },
  {
    verticalCode: "BUF34238",
    title: "الانترنت : استعد انطلق/ الأن سيمبسون.",
    author: "سيمبسون، الان.",
    callingCode: "004.65 سيم",
    publishDate: "1999",
  },
  {
    verticalCode: "BUF34239",
    title: "اللغات الاجنبية تعليمها وتعلمها/ تأليف نايف خرما",
    author: "نايف خرما",
    callingCode: "420.7 خرم",
    publishDate: "",
  },
  {
    verticalCode: "BUF34240",
    title:
      "صيانة وتأهيل الحاسب باستخدام Norton sysmworks 2000 / أيمن سيد درويش.",
    author: "درويش، أيمن سيد",
    callingCode: "621.38154 درو",
    publishDate: "2000",
  },
  {
    verticalCode: "BUF34241",
    title: "إليك أزف أشواقي/ مشهور سالم المزايدة.",
    author: "المزايدة، مشهور سالم. مؤلف",
    callingCode: "811.9565 مزا",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34242",
    title: "مدينة الرماد : شعر / نضال القاسم.",
    author: "نضال, القاسم.",
    callingCode: "811.9565 قاس",
    publishDate: "2005",
  },
  {
    verticalCode: "BUF34243",
    title:
      "العلمانيون وفلسطين : ‏ستون عامن من الفشل وماذا بعد؟! / تأليف عبد العزيز مصطفى كامل.",
    author: "كامل، عبد العزيز مصطفى",
    callingCode: "327.560564 كام",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34244",
    title: "الأيام / طه حسين.",
    author: "طه حسين، 1889-1973.",
    callingCode: "ق حسي",
    publishDate: "1977",
  },
  {
    verticalCode: "BUF34245",
    title:
      "تأثير زخارف سامراء الجصية في الفنون العربية الإسلامية / طاهر محمد هارون الغنميين .",
    author: "الغنميين، طاهر محمد هارون",
    callingCode: "704.9481 غنم",
    publishDate: "2021",
  },
  {
    verticalCode: "BUF34246",
    title: "أوراق الزيتون / محمود درويش.",
    author: "درويش، محمود، 1941-2008",
    callingCode: "811.9 درو",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34247",
    title: "خيط مسحور : شعر / علي العامري.",
    author: "العامري، علي.",
    callingCode: "811.9 عام",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34248",
    title: "عذرا أنا لست معاقا / عبد الله بن حمود البوسعيدي.",
    author: "البوسعيدي، عبد الله بن حمود",
    callingCode: "218 بوس",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34249",
    title: "السعادة الزوجية / كاميل صبري.",
    author: "صبري، كاميل",
    callingCode: "218.2 صبر",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34250",
    title: "الخلافات الزوجية / صبري كاميل.",
    author: "صبري، كاميل",
    callingCode: "306.84 صبر",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34251",
    title: "حب المراهقة / كاميل صبري.",
    author: "صبري، كاميل",
    callingCode: "155.51 صبر",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34252",
    title: "زواج الأقارب / كاميل صبري.",
    author: "صبري، كاميل",
    callingCode: "306.8 صبر",
    publishDate: "2007",
  },
  {
    verticalCode: "BUF34253",
    title:
      "في الجهود المسرحية العربية : من مارون نقاش إلى توفيق الحكيم / عبد الرحمن ياغي.",
    author: "ياغي، عبد الرحمن، 1924-",
    callingCode: "812.909 ياغ",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34254",
    title: "محطات في رحلة البحث عن الذات / محمد سمارة.",
    author: "محمد سمارة",
    callingCode: "155.2 سما",
    publishDate: "2003",
  },
  {
    verticalCode: "BUF34255",
    title:
      "500 فكرة رائعة لتنظيم كل شييء... / تأليف شيري بايكوفسكي ؛ ترجمة محمد عنان.",
    author: "بايكوفسكي، شيري.",
    callingCode: "658.4032 باي",
    publishDate: "1995",
  },
  {
    verticalCode: "BUF34256",
    title: "من أين أبدأ !!؟ / نبيلة الخطيب.",
    author: "الخطيب، نبيلة.",
    callingCode: "811.9565 خطي",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34257",
    title: "موسوعة الثوار والثورات عبر العصور/ آمال سعد.",
    author: "سعد، آمال",
    callingCode: "321.09409 سعد",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34258",
    title:
      "التفسير العظيم : المسمى تفسير القرآن العظيم/ للإمام المجتهد سلطان العلماء العز بن عبد السلام ؛ تحقيق قسم البحث العلمي في دار النور المبين للدراسات والشر.",
    author: "بن عبدالسلام، العز،",
    callingCode: "222.4 عبد",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34259",
    title:
      "التفسير العظيم : المسمى تفسير القرآن العظيم/ للإمام المجتهد سلطان العلماء العز بن عبد السلام ؛ تحقيق قسم البحث العلمي في دار النور المبين للدراسات والشر.",
    author: "بن عبدالسلام، العز،",
    callingCode: "222.4 عبد",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34260",
    title:
      "التفسير العظيم : المسمى تفسير القرآن العظيم/ للإمام المجتهد سلطان العلماء العز بن عبد السلام ؛ تحقيق قسم البحث العلمي في دار النور المبين للدراسات والشر.",
    author: "بن عبدالسلام، العز،",
    callingCode: "222.4 عبد",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34261",
    title:
      "التفسير العظيم : المسمى تفسير القرآن العظيم/ للإمام المجتهد سلطان العلماء العز بن عبد السلام ؛ تحقيق قسم البحث العلمي في دار النور المبين للدراسات والشر.",
    author: "بن عبدالسلام، العز،",
    callingCode: "222.4 عبد",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34262",
    title: "القرآن الكريم بالرسم العثماني.",
    author: "",
    callingCode: "221 قرآ",
    publishDate: "1979",
  },
  {
    verticalCode: "BUF34263",
    title: "القرآن الكريم.",
    author: "القرآن الكريم.",
    callingCode: "221 قرآ",
    publishDate: "2006",
  },
  {
    verticalCode: "BUF34264",
    title: "القرآن الكريم : برواية حفص عن عاصم بالرسم العثماني.",
    author: "",
    callingCode: "221 قرآ",
    publishDate: "2008",
  },
  {
    verticalCode: "BUF34265",
    title: "معالم الثقافة الإسلامية / عبد الكريم عثمان.",
    author: "عثمان، عبد الكريم",
    callingCode: "211 عثم",
    publishDate: "1990",
  },
  {
    verticalCode: "BUF34266",
    title:
      "شرح العقيدة الطحاوية / ابن أبي العز الحنفي ؛ حققها وراجعها جماعة من العلماء ؛ أخرج أحاديثها محمد ناصر الدين الألباني. التوضيح / بقلم زهير الشاويش.",
    author: "ابن أبي العز، علي بن علي بن محمد، 731-792 هـ.",
    callingCode: "240 حنف",
    publishDate: "1980",
  },
  {
    verticalCode: "BUF34267",
    title: "سرعة البديهة : سلاح الأذكياء / أحمد محمد عطيات.",
    author: "عطيات، أحمد محمد.",
    callingCode: "153.44 عطي",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34268",
    title: "أدب المهجر / عيسى الناعوري.",
    author: "الناعوري، عيسى، 1918-1985",
    callingCode: "810.9907 ناع",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34269",
    title: "الاختيار وقصص أخرى / أحمد رضوان عبد الله ناشد.",
    author: "ناشد، أحمد رضوان عبد الله",
    callingCode: "ق ناش",
    publishDate: "1994",
  },
  {
    verticalCode: "BUF34270",
    title: "نواقض الإسلام من الكتاب والسنة / صلاح الدين بن احمد الإدلبي.",
    author: "الإدلبي، صلاح الدين بن أحمد",
    callingCode: "218 ادل",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34271",
    title: "الدر الثمين في مدرسة الثلاثين / إعداد أحمد سليمان الرقب.",
    author: "الرقب، أحمد سليمان عوض، 1970- مؤلف.",
    callingCode: "271.3 رقب",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34272",
    title: "دع القلق و ابدأ الحياة / ابراهيم الفقي.",
    author: "الفقي، إبراهيم",
    callingCode: "152.46 فقي",
    publishDate: "[-199].",
  },
  {
    verticalCode: "BUF34273",
    title: "حجاب المرأة المسلمة في الكتاب والسنة / تأليف ناصر الدين الألباني.",
    author: "الألباني، محمد ناصر الدين، 1333-1418 هـ.",
    callingCode: "272.27 الب",
    publishDate: "1987",
  },
  {
    verticalCode: "BUF34274",
    title:
      "الواضح في احكام التجويد مع اسئلة للمناقشات وتمرينات. / محمد عصام مفلح القضاة.",
    author: "القضاة ، محمد عصام مفلح.",
    callingCode: "223.1 قضا",
    publishDate: "1998",
  },
  {
    verticalCode: "BUF34275",
    title: "فصل من شقاء العطر/ شعر هلال الفارع.",
    author: "الفارع، هلال",
    callingCode: "811.9 فار",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34276",
    title: "القدس مبنى ومعنى / عون معين القدومي.",
    author: "القدومي، عون معين، مؤلف.",
    callingCode: "956.411 قدو",
    publishDate: "2015",
  },
  {
    verticalCode: "BUF34277",
    title: "عتاب الساقيات / حسن البوريني.",
    author: "البوريني، الحسن بن محمد بن محمد، 963-1024 هـ.",
    callingCode: "811.9565 بور",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34278",
    title:
      "مبادئ علم النفس / الأستاذ الدكتور : عبد الرحمن عدس ، الدكتورة : نايفة قطامي.",
    author: "عدس، عبد الرحمن.",
    callingCode: "150 عدس",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34279",
    title:
      "الحج معجزة المكان والزمان / زغلول راغب محمد النجار [ويليه] تحقيق المقال في البسملة : (دراسة قرآنية) / تأليف محمد خازر المجالي، أحمد خالد شكري.",
    author: "النجار، زغلول راغب محمد.",
    callingCode: "271.53 زغل",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34280",
    title: "المحصل في فلسفة الحداثة / علي محمود العمري.",
    author: "العمري، علي محمود",
    callingCode: "190 عمر",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34281",
    title: "المحصل في فلسفة الحداثة / علي محمود العمري.",
    author: "العمري، علي محمود",
    callingCode: "190 عمر",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34282",
    title: "المحصل في فلسفة الحداثة / علي محمود العمري.",
    author: "العمري، علي محمود",
    callingCode: "190 عمر",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34283",
    title: "أين عمري / إحسان عبد القدوس.",
    author: "إحسان عبد القدوس، 1919-1990",
    callingCode: "ق عبد",
    publishDate: "1997",
  },
  {
    verticalCode: "BUF34284",
    title: "عبقرية الصديق / عباس محمود العقاد.",
    author: "عقاد، عباس محمود، 1889-1964.",
    callingCode: "956.031 عقا",
    publishDate: "1973",
  },
  {
    verticalCode: "BUF34285",
    title: "الظواهر الفلكية والجوية في القرآن الكريم / رفيق جميل شاكر الخانجي.",
    author: "الخانجي، رفيق جميل شاكر،",
    callingCode: "227.5 خان",
    publishDate: "2002",
  },
  {
    verticalCode: "BUF34286",
    title:
      "آيات الساعة العظمى : يأجوج ومأجوج-المسيح الدجال-الدابة / تأليف عصام يوسف.",
    author: "يوسف، عصام.",
    callingCode: "214.3 يوس",
    publishDate: "2014",
  },
  {
    verticalCode: "BUF34287",
    title: "المقصلة وجواسيس الشاباك الصهيوني / عبد الله البرغوثي.",
    author: "البرغوثي، عبد الله.",
    callingCode: "ق برغ",
    publishDate: "2013",
  },
  {
    verticalCode: "BUF34288",
    title: "صوت السهارى : عوض دوخي / إعداد فهد الفرس، يوسف عبد القادر الرشيد.",
    author: "الفرس، فهد، مؤلف.",
    callingCode: "782.0092 فرس",
    publishDate: "2012",
  },
  {
    verticalCode: "BUF34289",
    title:
      "أدب الحكاية الشعبية في فلسطين والأردن (في قوالب تمثيلية) / عمر عبد الرحمن الساريسي.",
    author: "الساريسي، عمر عبد الرحمن مؤلف.",
    callingCode: "398.209564 سار",
    publishDate: "2011",
  },
  {
    verticalCode: "BUF34290",
    title: "ألف ليلة وليلة.",
    author: "ألف ليلة وليلة",
    callingCode: "398.2041 الف",
    publishDate: "1981",
  },
  {
    verticalCode: "BUF34291",
    title: "ألف ليلة وليلة.",
    author: "ألف ليلة وليلة",
    callingCode: "398.2041 الف",
    publishDate: "1981",
  },
  {
    verticalCode: "BUF34292",
    title: "ألف ليلة وليلة.",
    author: "ألف ليلة وليلة",
    callingCode: "398.2041 الف",
    publishDate: "1981",
  },
  {
    verticalCode: "BUF34293",
    title: "ألف ليلة وليلة.",
    author: "ألف ليلة وليلة",
    callingCode: "398.2041 الف",
    publishDate: "1981",
  },
  {
    verticalCode: "BUF34294",
    title:
      "الأعلام الخمسة للشعر الإسلامي : العطار، رومي، السعدي، حالي، إقبال / ترجمه من الأردية والفارسية نثرا ونظما محمد حسن الأعظمي، الصاوي علي شعلان ؛ تحقيق مصطفى غالب.",
    author: "شعلان، الصاوي علي مترجم.",
    callingCode: "811.06 اعل",
    publishDate: "1982",
  },
  {
    verticalCode: "BUF34295",
    title:
      "فقه الزكاة : دراسة مقارنة لأحكامها و فلسفتها في ضوء القرآن و السنة / تأليف يوسف القرضاوي.",
    author: "قرضاوي، يوسف.",
    callingCode: "271.4 قرض",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34296",
    title:
      "الزاهر في غريب ألفاظ الشافعي الذي أودعه المزني في مختصره / صنفه أبي منصور الأزهري ؛ حققه محمد جبر الألفي.",
    author: "الأزهري، محمد بن أحمد بن الأزهر، 282-370 هـ.",
    callingCode: "217.3 ازه",
    publishDate: "1979",
  },
  {
    verticalCode: "BUF34297",
    title:
      "المبتكرون : اكتشافات العصر واختراعاته وإنجازاته / جون ديبولد ؛ ترجمة شحدة فارع.",
    author: "ديبولد، جون، و1926 مؤلف.",
    callingCode: "608 ديب",
    publishDate: "1993",
  },
  {
    verticalCode: "BUF34298",
    title:
      "الجرائم الصغرى عند العشائر الأردنية (1900-1986) / تأليف أحمد عويدي العبادي.",
    author: "العبادي، أحمد عويدي",
    callingCode: "347.9565 عبا",
    publishDate: "1987",
  },
];
